services:
  db:
    image: postgis/postgis:15-3.3
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  web:
    build: ./backend
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./backend:/code
    - ./backend/jwt_private.pem:/code/jwt_private.pem
    - ./backend/jwt_public.pem:/code/jwt_public.pem
    expose:
      - "8000"  # Expose le port pour Nginx, mais n'expose pas à l'extérieur
    depends_on:
      - db
    networks:
      - backend

  frontend:
    build: ./frontend
    expose:
      - "5000"
    depends_on:
      - web
    networks:
      - backend
  nginx:
    build: ./frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - web
      - frontend
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata:
