services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - back-end

  web:
    build: ./backend
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - web
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  pgdata:
