# Generated by Django 5.1.1 on 2024-10-17 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_user_email_activation_exp_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 18, 10, 3, 9, 724840, tzinfo=datetime.timezone.utc)),
        ),
    ]
