# Generated by Django 5.1.1 on 2024-10-18 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_profession_options_profession_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 13, 38, 46, 422361, tzinfo=datetime.timezone.utc)),
        ),
    ]
