# Generated by Django 5.1.1 on 2024-10-11 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_user_email_activation_exp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appntmnt_datetime_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appntmnt_datetime_start',
            new_name='start',
        ),
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 11, 0, 4, 780368, tzinfo=datetime.timezone.utc)),
        ),
    ]
