# Generated by Django 5.1.1 on 2024-10-31 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_user_email_activation_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 1, 3, 9, 19, 706846, tzinfo=datetime.timezone.utc)),
        ),
    ]
