# Generated by Django 5.1.1 on 2024-10-11 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_user_email_activation_exp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='apppntmnt_location',
            new_name='appntmnt_location',
        ),
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 12, 11, 14, 40, 733789, tzinfo=datetime.timezone.utc)),
        ),
    ]
