# Generated by Django 5.1.1 on 2024-10-14 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_rename_apppntmnt_location_appointment_appntmnt_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 7, 29, 56, 437375, tzinfo=datetime.timezone.utc)),
        ),
    ]
