# Generated by Django 5.1.1 on 2024-11-03 19:20

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_user_email_activation_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_description',
        ),
        migrations.AddField(
            model_name='professional',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='services', to='apps.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='professional',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.profession'),
        ),
        migrations.AlterField(
            model_name='service',
            name='professionals',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='apps.professional'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 19, 20, 9, 39147, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=6, unique=True)),
                ('custom_description', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_services', to='apps.professional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_services', to='apps.service')),
            ],
            options={
                'verbose_name': 'Professional service description',
                'verbose_name_plural': 'Professional services description',
                'unique_together': {('professional', 'service')},
            },
        ),
    ]
