# Generated by Django 5.1.1 on 2024-10-14 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_user_email_activation_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 11, 23, 58, 834921, tzinfo=datetime.timezone.utc)),
        ),
    ]
