# Generated by Django 5.1.1 on 2024-11-03 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_profession_custom_profession_alter_profession_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 22, 34, 29, 551876, tzinfo=datetime.timezone.utc)),
        ),
    ]
