# Generated by Django 5.1.1 on 2024-11-05 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_remove_professionalservice_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 1, 33, 9, 62375, tzinfo=datetime.timezone.utc)),
        ),
    ]
