# Generated by Django 5.1.1 on 2024-11-05 02:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_remove_profession_proposed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 2, 51, 14, 532204, tzinfo=datetime.timezone.utc)),
        ),
    ]
