# Generated by Django 5.1.1 on 2024-11-05 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_professional_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 10, 5, 8, 921731, tzinfo=datetime.timezone.utc)),
        ),
    ]
