# Generated by Django 5.1.1 on 2024-11-05 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_alter_user_email_activation_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='proposed_by',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 20, 45, 59, 363380, tzinfo=datetime.timezone.utc)),
        ),
    ]
