# Generated by Django 5.1.1 on 2024-11-05 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_alter_profession_proposed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 21, 56, 1, 907800, tzinfo=datetime.timezone.utc)),
        ),
    ]
