# Generated by Django 5.1.1 on 2024-11-06 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_alter_user_email_activation_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='proposed_by',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 0, 19, 6, 120390, tzinfo=datetime.timezone.utc)),
        ),
    ]
