# Generated by Django 5.1.1 on 2024-11-06 10:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_alter_profession_proposed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_professions', to='apps.professional'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals', to='apps.profession'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 10, 44, 33, 528674, tzinfo=datetime.timezone.utc)),
        ),
    ]
