# Generated by Django 5.1.1 on 2024-11-06 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_alter_profession_proposed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 10, 48, 37, 754650, tzinfo=datetime.timezone.utc)),
        ),
    ]
