# Generated by Django 5.1.1 on 2024-11-06 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_alter_user_email_activation_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='custom_profession',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='custom_profession_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 12, 23, 58, 378774, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
    ]
