# Generated by Django 5.1.1 on 2024-11-07 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_alter_professional_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_activation_exp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 20, 27, 37, 608063, tzinfo=datetime.timezone.utc)),
        ),
    ]
