# Generated by Django 5.1.1 on 2024-11-07 20:28

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_alter_user_email_activation_exp'),
    ]

    operations = [
        UnaccentExtension()
    ]
